---
- hosts: consulweb
  connection: ssh
  roles:
    - role: linuxhq.consul
      consul_client_addr: 0.0.0.0
      consul_datacenter: dhc
      consul_use_initd: true
      consul_node_name: "{{ inventory_hostname }}"
      consul_server: false
      consul_telemetry: {}
      consul_leader: 192.168.10.115
      consul_start_join:
        - 192.168.10.116
        - 192.168.10.117
        - 192.168.10.150
        - 192.168.10.191
      consul_ui: True
      consul_watches: []
  #user: name=www-data comment="www-data" uid=1040 group=nginx
