---
- hosts: consulweb
  connection: ssh
  vars_files:
    - vars/consweb
  roles:
    - role: linuxhq.consul

- hosts: consulserver
  connection: ssh
  vars_files:
    - vars/consulwebserver
  roles:
    - role: linuxhq.consul
