---
- hosts: consulweb
  connection: ssh
  roles:
    - role: linuxhq.consul
      consul_client_addr: 0.0.0.0
      consul_datacenter: dhc-kore
      consul_use_initd: true
      consul_node_name: "{{ inventory_hostname }}"
      consul_server: false
      consul_telemetry: {}
      consul_leader: 192.168.10.115
      consul_start_join:
        - 192.168.10.116
        - 192.168.10.117
        - 192.168.10.150
        - 192.168.10.191
      consul_ui: True
      consul_watches: []
      vars_files:
        - /vars/external_vars.yml

      consul_services_root:
        services:
          - id: webservice-poll
            name: webservice-poll
            tags:
             - poll
            port: 80
            checks:
             - name: 'Sys check '
               script: 'curl localhost >/dev/null 2>&1 '
               interval: 5s
               timeout: 1s
             - name: HTTP on port 80
               http: http://localhost:80/
               interval: 5s
               timeout: 1s
          - id: webservice-poll
            name: webservice-poll
            tags:
             - poll
            port: 9090
            checks:
             - name: 'Sys check '
               script: 'curl localhost >/dev/null 2>&1 '
               interval: 5s
               timeout: 1s
             - name: HTTP on port 9090
               http: http://localhost:80/
               interval: 5s
               timeout: 1s
      consul_services:
        - service:
            name: "consulweb"
            tags:
              - "consulwebport80"
            address: "127.0.0.1"
            port: 80
            checks:
              - name: "webhealthcheck"
                interval: "10s"
                timeout: "1s"
                script: "curl localhost >/dev/null 2>&1"

- hosts: consulserver
  connection: ssh
  roles:
    - role: linuxhq.consul
      consul_client_addr: 0.0.0.0
      consul_datacenter: dhc-kore
      consul_use_initd: true
      consul_node_name: "{{ inventory_hostname }}"
      consul_server: true
      consul_dynamic_bind: true
      consul_bind_ip: "{{ ansible_ssh_host }}"
      consul_bootstrap: true
      consul_telemetry: {}
      consul_start_join:
        - 192.168.10.116
        - 192.168.10.150
        - 192.168.10.191
      consul_ui: True
      consul_watches: []
