---
# Playbook Consul playbook
- hosts: consulweb
  connection: ssh
  
  vars_files:
    - "{{_varsPath}}/consweb"
  roles:
    - role: linuxhq.consul

- hosts: consulserver
  connection: ssh
  
  vars_files:
    - "{{_varsPath}}/consulwebserver"
  roles:
    - role: linuxhq.consul
