--- 
# Playbook monit playbook
- name: Playbook for monit 
  hosts: monit-onprem
  gather_facts: True
  user: root

  vars_files:
   - "{{ _varsPath }}/monitvars"

  roles:
    - role: pgolm.monit

  tasks:
    - include: "{{ tasks }}/monit.yml"
